baseURL = 'https://tedpinkerton.ca/'
languageCode = 'en-us'
title = 'Ted Pinkerton'
theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "posts"

    url = "/posts/"

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/pages/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/RunnersNum40/tedpinkerton.ca"
    weight = 3
    
    pre = "<span data-feather='github'></span>"
    
  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/ted-pinkerton/"
    weight = 4
    
    pre = "<span data-feather='linkedin'></span>"


[params]
  # Description to display on homepage
  description = "Projects, Skills, and Portfolio"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  # customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo", "ted pinkerton", "portfolio"]

  pygmentsStyle = "dracula"

[context.production.environment]
  HUGO_VERSION = "0.105.0"
