baseURL: "https://tedpinkerton.ca/"
title: Ted Pinkerton
theme: hello-friend-ng

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

menu:
  main:
    - name: about
      url: about
      weight: 1
    - name: skills
      url: skills
      weight: 2
    - name: projects
      url: projects
      weight: 3
    - name: tags
      url: tags
      weight: 3

taxonomies:
  category: categories
  tag: tags
  series: series

params:
  author: Ted Pinkerton
  env: production
  description: "Ted Pinkerton, a third-year Engineering Science student at the University of Toronto specializing in Machine Intelligence, showcases his skills and projects in robotics, computer science, and mechanical design."
  keywords:
    [
      Ted Pinkerton,
      Portfolio,
      Engineering Science,
      Machine Intelligence,
      Robotics,
      University of Toronto,
      Software Development,
      Mechanical Design,
      Python,
      AI Portfolio,
      Project Showcase,
      Computational Thinking,
      Innovation in Robotics,
      Technology,
      Machine Learning,
      Artificial Intelligence,
      Developer,
      Engineering Projects,
      Analytical Skills,
      Problem Solving,
      Programming,
      Tech Innovations,
      Algorithm Design,
      Data Science,
    ]
  images: [""]
  defaultTheme: auto
  # disableThemeToggle: true
  ShowCodeCopyButtons: true
  homeSubtitle: >
    I am an [Engineering Science](https://engsci.utoronto.ca/) student at the [University of Toronto](https://www.engineering.utoronto.ca/), currently in my third year with a focus on Machine Intelligence Engineering. My interests span software development, robotics, control systems, and artificial intelligence. I am particularly fascinated by the interplay between hardware and software systems, especially within the realm of robotics.

  social:
    - name: git
      url: "https://github.com/RunnersNum40/"
    - name: linkedin
      url: "https://www.linkedin.com/in/ted-pinkerton/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/7675722/runnersnum45"
    - name: email
      url: mailto:ted.pinkerton@mail.utoronto.ca
  logo:
    logoText: cd ~

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    style: dracula
    linenos: true
    guessSyntax: true
    codeFences: true
    anchorLineNos: true

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

# Netlify config info
context:
  production:
    environment:
      HUGO_VERSION: 0.119.0
