baseURL: "https://tedpinkerton.ca/"
title: Ted Pinkerton
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

menu:
  main:
    - name: about
      url: about
      weight: 1
      pre: "cd ~/"
    - name: skills
      url: skills
      weight: 2
      pre: "cd ~/"
    - name: projects
      url: projects
      weight: 3
      pre: "cd ~/"

taxonomies:
  category: categories
  tag: tags
  series: series

params:
  disableThemeToggle: true
  label:
    text: "~"
  env: production
  description: Ted Pinkerton's portfolio and project showcase for robotics, software development, mechanical design, and engineering
  keywords:
    [
      personal,
      website,
      python,
      development,
      developer,
      ted pinkerton,
      machine intelligence,
      ai,
      portfolio,
      projects,
      engineering science,
      engineer,
      robotics,
    ]
  defaultTheme: auto
  ShowCodeCopyButtons: true

  profileMode:
    enabled: true
    title: Who am I?
    subtitle: >
      I am an [Engineering Science](https://engsci.utoronto.ca/) student at the [University of Toronto](https://www.engineering.utoronto.ca/).
      Currently on my Professional Experience Year (PEY) as a Front-end Intern at BioConnect, I am set to graduate in 2025 with a focus on machine intelligence engineering.
      I'm drawn towards software engineering, particularly in reinforcement learning for robotics and space robotics applications.
  socialIcons:
    - name: github
      url: "https://github.com/RunnersNum40/"
    - name: linkedin
      url: "https://www.linkedin.com/in/ted-pinkerton/"
    - name: email
      url: mailto:ted.pinkerton@mail.utoronto.ca

markup:
  # Allow inline html in markdown
  goldmark:
    renderer:
      unsafe: true

  highlight:
    style: dracula
    linenos: true
    guessSyntax: true
    codeFences: true
    anchorLineNos: true

# Configured for maximum privacy of visitors
privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

# Netlify config info
context:
  production:
    environment:
      HUGO_VERSION: 0.105.0
