baseURL: 'https://tedpinkerton.ca/'
title: Ted Pinkerton
theme: paige

enablerobotstxt: true

menu:
    main:
        - name: About Me
          url: about
          weight: 1
        - name: Skills
          url: skills
          weight: 2
        - name: Projects
          url: projects
          weight: 3
        # - name: Tags
        #   url: tags
        #   weight: 3

paige:
  # date_format: "2006 January 2" # Hugo date format for page dates
  # hide_theme_comment: true # Don't put a link to this project in a code comment
  # hide_theme_link: true # Don't put a link to this project in the footer

markup:
  goldmark:
    renderer:
      unsafe: true
  tableofcontents:
    endlevel: 6
    ordered: true
    startlevel: 2

# Netlify config info
context:
    production:
        environment:
            HUGO_VERSION: 0.105.0
